### ISSUE TITLE
Hard to use

### ISSUE THREAD

**Issue by Flawake** [MarcvdSluys/SolTrack-Arduino#1]
I think this program is too hard to use, when executing example.ino it says it has to be in a folder called example.
Then you get the question if the folder should automaticly be created, so everyone clicks yes.
when compiling example.ino you get the error: undifined reference to SolTrack(STTime, STLocation, STPosition*, int, int, int, int)

What needs to be done is placing Soltrack.ino in the same folder as your own script, but that is not documented.
I think it would be a improvement if that is stated at the readme.md or in a new file called documentation.

**Comment by MarcvdSluys** [comment]
I think this is basic Arduino/computing stuff and may be system-dependent: many Arduino programs for the PC want the directory to have the same name as the scratch file (see e.g. [this page](https://arduino.stackexchange.com/q/32619/43342)) but there's no reason why you can't hack [this Makefile](https://shallowsky.com/software/arduino/arduino-cmdline.html) to do otherwise.  I added a footnote on this.

If you call Soltrack in the same directory, but it is not there, it won't work, but that is nomal; either put it there or call it in the place where it _does_ sit.  If I try to start Notepad from the directory `/HereIsMyNotepad/` but Notepad isn't there, it won't work.  Either copy Notepad there or start it from the directory where it really is.

I think it would be inefficient to provide a basic Arduino/computing course with each scratch file - you can probably find them online elsewhere.
